### PR TITLE
Osx arm64 and aarch64

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I'll add aarch later:

```
 ERROR: dependencies ‘raster’, ‘plyr’, ‘terra’ are not available for package ‘satellite’
```

**Comment by ocefpaf** [comment]
Humm, osx-arm64 is complaining that 

r-raster: https://github.com/conda-forge/r-raster-feedstock/pull/45
r-plyr: https://github.com/conda-forge/r-plyr-feedstock/pull/11
r-terra: https://github.com/conda-forge/r-terra-feedstock/pull/99

are not available.


@mfansler if you are not too busy, do you have any idea what is going on here? I don't have a M1 mac to test this but a,

```
CONDA_OVERRIDE_OSX=14 CONDA_SUBDIR=osx-arm64 micromamba env create --name TMP r-terra r-plyr r-raster --dry-run
```

Works :-/

**Comment by danielnachun** [comment]
I have an Apple Silicon Macbook and I will test this locally.  I have seen this happen before if the packages are not actually built correctly, though the PRs you have linked seem to rule out the more trivial reasons for this to happen.

**Comment by danielnachun** [comment]
Actually the cause of the problem is clear now - the ARM migrator PR (https://github.com/conda-forge/r-satellite-feedstock/pull/14) shows that you need to have all the packages in the `build` requirements as well as in `host`.  It might be better to start with that PR, which is still failing but has more of the necessary changes for this work correctly.

**Comment by danielnachun** [comment]
Superseded by https://github.com/conda-forge/r-satellite-feedstock/pull/14

**Pull request closed without merging**
